server:
  port: 9090

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

logging:
  level:
    root: INFO
    com.deezzex.gateway: DEBUG

banner:
  location: classpath:banner.txt

gateway:
  route:
    fiat:
      url: http://localhost:8081
    crypto:
      url: http://localhost:8082
    aggregator:
      url: http://localhost:8083
    user:
      url: http://localhost:8084

