server:
  port: 8082
  servlet:
    context-path: /crypto

spring:
  application:
    name: crypto-service
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:8099/crypto
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  level:
    root: INFO
    com.deezzex.crypto: DEBUG  # Замінити на свій базовий пакет, щоб мати більше логів

# Налаштування банера при старті додатку
banner:
  location: classpath:banner.txt
